# Generated by Django 5.0.6 on 2025-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3),
        ),
    ]
