# Generated by Django 5.0.6 on 2025-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_factura_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares Americanos')], default='ARS', max_length=3),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
