# Generated by Django 5.0.6 on 2026-01-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_factura_observaciones_proyecto_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('meet', 'Meet'), ('llamada', 'Llamada'), ('entrega', 'Entrega'), ('otro', 'Otro')], default='meet', max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recordatorio_minutos_antes', models.PositiveIntegerField(default=1440)),
                ('recordatorio_enviado_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='webapp.cliente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='webapp.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares Americanos')], default='ARS', max_length=3)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=1)),
                ('dias_antes_recordatorio', models.PositiveSmallIntegerField(default=5)),
                ('proximo_vencimiento', models.DateField(blank=True, null=True)),
                ('ultimo_recordatorio_enviado', models.DateField(blank=True, null=True)),
                ('ultimo_periodo_facturado', models.DateField(blank=True, null=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidad', to='webapp.proyecto')),
            ],
        ),
    ]
