# Generated by Django 5.0.6 on 2026-08-26 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_evento_proyectomensualidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['inicio']},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_inicio', '-id']},
        ),
        migrations.AlterModelOptions(
            name='proyectomensualidad',
            options={'ordering': ['proximo_vencimiento'], 'verbose_name_plural': 'Mensualidades'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Link de Meet, dirección, etc.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_cobro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='periodo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectomensualidad',
            name='generar_factura_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('potencial', 'Potencial'), ('inactivo', 'Inactivo')], default='potencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='factura',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='webapp.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('terminado', 'Terminado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('llamada', 'Llamada'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión')], default='nota', max_length=20)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='webapp.cliente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to='webapp.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
