# Generated by Django 5.0.6 on 2026-08-26 20:02

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_cliente_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('casa', models.CharField(choices=[('bolsa', 'Dólar MEP / Bolsa'), ('blue', 'Dólar Blue'), ('oficial', 'Dólar Oficial'), ('cripto', 'Dólar Cripto'), ('tarjeta', 'Dólar Tarjeta')], default=webapp.models._casa_por_defecto, max_length=20)),
                ('compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente', models.CharField(choices=[('api', 'API'), ('manual', 'Cargado a mano')], default='manual', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'casa')},
            },
        ),
    ]
