# Generated by Django 5.0.6 on 2026-08-26 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_factura_tipo_cambio_tipocambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(choices=[('indigo', 'Índigo'), ('sky', 'Celeste'), ('violet', 'Violeta'), ('emerald', 'Verde'), ('amber', 'Ámbar'), ('rose', 'Rosa'), ('slate', 'Gris')], default='indigo', max_length=20)),
                ('tipo', models.CharField(choices=[('abierta', 'En curso'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='abierta', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='webapp.pipeline')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares Americanos')], default='ARS', max_length=3)),
                ('cierre_estimado', models.DateField(blank=True, null=True)),
                ('cerrado_en', models.DateField(blank=True, null=True)),
                ('motivo_cierre', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='webapp.cliente')),
                ('proyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='webapp.proyecto')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='webapp.etapa')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='webapp.pipeline')),
            ],
            options={
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('vence', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('completada', models.BooleanField(default=False)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='webapp.cliente')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='webapp.deal')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='webapp.proyecto')),
            ],
            options={
                'ordering': ['completada', 'vence', 'id'],
            },
        ),
    ]
