"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f$jo19ev_mhiew^nfumeule1ojsy+80#+pio0get=5!5wwh)10'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['nachogakd.pythonanywhere.com', '127.0.0.1', 'supregsolutions.com', 'www.supregsolutions.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webapp.context_processors.crm_badges',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [os.path.join(BASE_DIR, "webapp/static")]
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "webapp/staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

CSRF_TRUSTED_ORIGINS = [
    "https://supregsolutions.com",
    "https://www.supregsolutions.com", 
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "supregsolutions@gmail.com"
EMAIL_HOST_PASSWORD = "jbmh qdbq hbdt sspn"
DEFAULT_FROM_EMAIL = "SupReg CRM <supregsolutions@gmail.com>"

# a quién le llegan los recordatorios internos
CRM_ALERT_EMAILS = ["supregsolutions@gmail.com", "nachog.akd@hotmail.com"]

# ---- CRM ----
# casa de cambio que se usa para consolidar todo en dólares
# opciones: bolsa (MEP), blue, oficial, cripto, tarjeta
CRM_CASA_DOLAR = "bolsa"

# vencimiento por defecto de una factura nueva (días desde la emisión)
CRM_DIAS_VENCIMIENTO_FACTURA = 15
TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_TZ = True



# ---- Celery (opcional) ----
# Sólo se usa si el servidor tiene Redis. Si no, los mismos trabajos se corren
# con `python manage.py crm_cron` desde un cron o una Scheduled Task.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/2")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/3")
CELERY_TIMEZONE = TIME_ZONE

try:
    from celery.schedules import crontab
except ImportError:
    CELERY_BEAT_SCHEDULE = {}
else:
    CELERY_BEAT_SCHEDULE = {
        "crm_cotizacion_diaria_0830": {
            "task": "webapp.tasks.sincronizar_cotizaciones",
            "schedule": crontab(hour=8, minute=30),
        },
        "crm_mensualidades_diario_0900": {
            "task": "webapp.tasks.enviar_recordatorios_mensualidades",
            "schedule": crontab(hour=9, minute=0),
        },
        "crm_eventos_cada_5_min": {
            "task": "webapp.tasks.enviar_recordatorios_eventos",
            "schedule": crontab(minute="*/5"),
        },
        "crm_facturas_vencidas_lunes_0930": {
            "task": "webapp.tasks.avisar_facturas_vencidas",
            "schedule": crontab(day_of_week=1, hour=9, minute=30),
        },
    }
